# Generated by Django 4.2.16 on 2024-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
