# Generated by Django 5.1.3 on 2024-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_alter_notifications_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('FRIEND_REQUEST', 'Friend Request'), ('MATCH_INVITE', 'Match Invite'), ('TOURNAMENT_INVITE', 'Tournament Invite'), ('CHAT_MESSAGE', 'Chat Message'), ('FRIEND_REQUEST_ACCEPTED', 'Friend Request Accepted'), ('FRIEND_REQUEST_DENIED', 'Friend Request Rejected')], max_length=50),
        ),
    ]
