services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /Users/rel-fila/Desktop/database:/var/lib/postgresql/data
    networks:
      - my-network
    restart: always
networks:
  my-network:
    driver: bridge