version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - my-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - my-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # React Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  database:
    driver: local
