<<<<<<< HEAD
# Generated by Django 4.2.14 on 2024-07-19 08:07
=======
# Generated by Django 4.2.16 on 2024-10-15 09:19
>>>>>>> origin/talal

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Block_mute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(max_length=200)),
                ('last_message_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.conversation')),
            ],
        ),
>>>>>>> origin/talal
    ]
