<<<<<<< HEAD
# Generated by Django 4.2.14 on 2024-07-19 08:08

=======
# Generated by Django 4.2.16 on 2024-10-15 09:19

from django.conf import settings
>>>>>>> origin/talal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('User', '0002_initial'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/talal
        ('Chat', '0001_initial'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(max_length=200)),
                ('last_message_time', models.DateTimeField(auto_now_add=True)),
                ('uid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='User.user')),
                ('uid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Block_mute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user1', to='User.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user2', to='User.user')),
            ],
=======
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='uid1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='uid2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block_mute',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block_mute',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user2', to=settings.AUTH_USER_MODEL),
>>>>>>> origin/talal
        ),
    ]
