# Generated by Django 4.2.13 on 2024-06-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('cover', models.ImageField(upload_to='covers/')),
                ('bio', models.TextField(max_length=200)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('stat', models.BooleanField(default=False)),
            ],
        ),
    ]
