# Generated by Django 4.2.16 on 2024-10-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default_cover.png', null=True, upload_to='covers/'),
        ),
    ]
