# Generated by Django 4.2.16 on 2024-11-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
