# Generated by Django 4.2.16 on 2024-12-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
