# Generated by Django 4.2.16 on 2024-09-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='./../media/avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
