# Generated by Django 4.2.16 on 2025-01-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
