# Generated by Django 4.2.16 on 2024-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='users_num',
            field=models.IntegerField(default=0),
        ),
    ]
