# Generated by Django 4.2.16 on 2024-11-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0002_tournaments_users_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='users',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='users_num',
        ),
    ]
