<<<<<<< HEAD
# Generated by Django 4.2.14 on 2024-07-19 08:07

from django.db import migrations
=======
# Generated by Django 4.2.16 on 2024-10-12 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> origin/talal


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
    ]

    operations = [
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.IntegerField(default=0)),
                ('loser_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_game', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
>>>>>>> origin/talal
    ]
